<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.1.1 (Python 3.7.3 on linux)" generated="20191213 09:50:33.584" rpa="false">
<suite id="s1" name="Tests" source="/tests">
<suite id="s1-s1" name="Api" source="/tests/api">
<suite id="s1-s1-s1" name="Api Tests" source="/tests/api/api_tests.robot">
<test id="s1-s1-s1-t1" name="Is Service Healthy">
<kw name="Create Session" library="RequestsLibrary">
<doc>Create Session: create a HTTP session to a server</doc>
<arguments>
<arg>app</arg>
<arg>${APP_URL}</arg>
</arguments>
<msg timestamp="20191213 09:50:34.225" level="INFO">Creating Session using : alias=app, url=http://localhost:8080, headers={},                     cookies={}, auth=None, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<status status="PASS" starttime="20191213 09:50:34.224" endtime="20191213 09:50:34.225"></status>
</kw>
<kw name="Get Request" library="RequestsLibrary">
<doc>Send a GET request on the session object found using the
given `alias`</doc>
<arguments>
<arg>app</arg>
<arg>/healthy</arg>
</arguments>
<assign>
<var>${RESPONSE}</var>
</assign>
<msg timestamp="20191213 09:50:34.226" level="INFO">GET Request using : uri=/healthy, params=None, allow_redirects=True, timeout=None
headers={'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} 
data=None 
json=None</msg>
<msg timestamp="20191213 09:50:34.230" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f8360bd96d8&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /healthy</msg>
<msg timestamp="20191213 09:50:34.432" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f8360bd9978&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /healthy</msg>
<msg timestamp="20191213 09:50:34.835" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f8360bd9b38&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /healthy</msg>
<msg timestamp="20191213 09:50:34.838" level="FAIL">ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /healthy (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f8360bd9cf8&gt;: Failed to establish a new connection: [Errno 111] Connection refused'))</msg>
<status status="FAIL" starttime="20191213 09:50:34.226" endtime="20191213 09:50:34.838"></status>
</kw>
<status status="FAIL" starttime="20191213 09:50:34.223" endtime="20191213 09:50:34.838" critical="yes">ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /healthy (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f8360bd9cf8&gt;: Failed to establish a new connection: [Errno 111] Connection refused'))</status>
</test>
<status status="FAIL" starttime="20191213 09:50:33.637" endtime="20191213 09:50:34.841"></status>
</suite>
<status status="FAIL" starttime="20191213 09:50:33.633" endtime="20191213 09:50:34.845"></status>
</suite>
<suite id="s1-s2" name="Create User" source="/tests/create_user">
<suite id="s1-s2-s1" name="Create User" source="/tests/create_user/create_user.robot">
<test id="s1-s2-s1-t1" name="User creation passes">
<kw name="Fail" library="BuiltIn">
<doc>Fails the test with the given message and optionally alters its tags.</doc>
<arguments>
<arg>Not Implemented</arg>
</arguments>
<msg timestamp="20191213 09:50:34.867" level="FAIL">Not Implemented</msg>
<status status="FAIL" starttime="20191213 09:50:34.866" endtime="20191213 09:50:34.867"></status>
</kw>
<status status="FAIL" starttime="20191213 09:50:34.865" endtime="20191213 09:50:34.868" critical="yes">Not Implemented</status>
</test>
<status status="FAIL" starttime="20191213 09:50:34.852" endtime="20191213 09:50:34.870"></status>
</suite>
<status status="FAIL" starttime="20191213 09:50:34.848" endtime="20191213 09:50:34.875"></status>
</suite>
<status status="FAIL" starttime="20191213 09:50:33.585" endtime="20191213 09:50:34.878"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="2">Critical Tests</stat>
<stat pass="0" fail="2">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="2" id="s1" name="Tests">Tests</stat>
<stat pass="0" fail="1" id="s1-s1" name="Api">Tests.Api</stat>
<stat pass="0" fail="1" id="s1-s1-s1" name="Api Tests">Tests.Api.Api Tests</stat>
<stat pass="0" fail="1" id="s1-s2" name="Create User">Tests.Create User</stat>
<stat pass="0" fail="1" id="s1-s2-s1" name="Create User">Tests.Create User.Create User</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20191213 09:50:34.230" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f8360bd96d8&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /healthy</msg>
<msg timestamp="20191213 09:50:34.432" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f8360bd9978&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /healthy</msg>
<msg timestamp="20191213 09:50:34.835" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f8360bd9b38&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /healthy</msg>
</errors>
</robot>
